### PR TITLE
Onboard dependabot workflows

### PR DESCRIPTION
**Pull request by purple-team-service-user**
Generated by https://github.com/adevinta/vulcan-cicd/actions/runs/6183688453

### CODE REVIEW

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185343583

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6185382334

**Review by manelmontilla — APPROVED** [review]
LGTM

**Comment by purple-team-service-user** [comment]
Updated by https://github.com/adevinta/vulcan-cicd/actions/runs/6225207258

**Review by manelmontilla — APPROVED** [review]
LGTM

**Pull request merged**
